version: '3'
services:
  gpt-researcher:
    image: assafelovic/gpt-researcher
    build: ./
    environment: 
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    ports:
      - 8000:8000